version: 2

workflows:
  version: 2
  test:
    jobs:
      - test-2.4
      - test-2.5
      - test-2.6
      - test-2.7
      - test-jruby-9.2

ruby-docker-template: &ruby-docker-template
  steps:
    - checkout
    - run: |
        if [[ $CIRCLE_JOB == test-jruby* ]]; then
          gem install jruby-openssl; # required by bundler, no effect on Ruby MRI
          sudo apt-get update -y && sudo apt-get install -y build-essential
        fi
    - run: ruby -v
    - run: gem install bundler -v 1.17.3
    - run: bundle install
    - run: mkdir ./rspec
    - run: bundle exec rspec --format progress --format RspecJunitFormatter -o ./rspec/rspec.xml spec
    - store_test_results:
        path: ./rspec
    - store_artifacts:
        path: ./rspec

jobs:
  test-2.4:
    <<: *ruby-docker-template
    docker:
      - image: circleci/ruby:2.4
      - image: consul
      - image: redis
      - image: amazon/dynamodb-local
  test-2.5:
    <<: *ruby-docker-template
    docker:
      - image: circleci/ruby:2.5
      - image: consul
      - image: redis
      - image: amazon/dynamodb-local
  test-2.6:
    <<: *ruby-docker-template
    docker:
      - image: circleci/ruby:2.6
      - image: consul
      - image: redis
      - image: amazon/dynamodb-local
  test-2.7:
    <<: *ruby-docker-template
    docker:
      - image: circleci/ruby:2.7
      - image: consul
      - image: redis
      - image: amazon/dynamodb-local
  test-jruby-9.2:
    <<: *ruby-docker-template
    docker:
      - image: circleci/jruby:9.2-jdk
      - image: consul
      - image: redis
      - image: amazon/dynamodb-local
